### ISSUE TITLE
Fix sizes of info boxes

### ISSUE THREAD

**Issue by gaurav613** [gaurav613/fydp_bess#35]
Right now, it looks like the boxes on the home page, with the information, are of different sizes - which may be due to dynamic sizing. It would look better if they were of the same size:
![design](https://user-images.githubusercontent.com/33888368/157909043-1b765747-ce5b-43f6-b9e4-b87cfb1373c8.JPG)

**Comment by Kyle199910** [comment]
Looked at the cards, they all already have the same width( i checked and measured with ruler), so i made the cards also have the same height to make them look more identical

**Comment by Kyle199910** [comment]
in my PR
